-- Standard-Kategorien (Seeding)
INSERT INTO categories (name, max_budget_eur) VALUES ('Haupteinkommen', 0.0);
INSERT INTO categories (name, max_budget_eur) VALUES ('Nebeneinkommen', 0.0);
INSERT INTO categories (name, max_budget_eur) VALUES ('Staatliche Leistungen/Transfers', 0.0);
INSERT INTO categories (name, max_budget_eur) VALUES ('Kapitaleinkünfte', 0.0);
INSERT INTO categories (name, max_budget_eur) VALUES ('Sonstige Einnahmen', 0.0);
INSERT INTO categories (name, max_budget_eur) VALUES ('Wohnen', 0.0);
INSERT INTO categories (name, max_budget_eur) VALUES ('Versicherungen', 0.0);
INSERT INTO categories (name, max_budget_eur) VALUES ('Mobilität (Fix)', 0.0);
INSERT INTO categories (name, max_budget_eur) VALUES ('Kommunikation/Medien', 0.0);
INSERT INTO categories (name, max_budget_eur) VALUES ('Finanzen/Sparen (Fix)', 0.0);
INSERT INTO categories (name, max_budget_eur) VALUES ('Abonnements/Mitgliedschaften', 0.0);
INSERT INTO categories (name, max_budget_eur) VALUES ('Lebensmittel & Haushalt', 0.0);
INSERT INTO categories (name, max_budget_eur) VALUES ('Mobilität (Variabel)', 0.0);
INSERT INTO categories (name, max_budget_eur) VALUES ('Kleidung & Körperpflege', 0.0);
INSERT INTO categories (name, max_budget_eur) VALUES ('Gesundheit', 0.0);
INSERT INTO categories (name, max_budget_eur) VALUES ('Freizeit & Unterhaltung', 0.0);
INSERT INTO categories (name, max_budget_eur) VALUES ('Kinder/Haustiere', 0.0);
INSERT INTO categories (name, max_budget_eur) VALUES ('Urlaub & Reisen', 0.0);
INSERT INTO categories (name, max_budget_eur) VALUES ('Geschenke & Spenden', 0.0);
INSERT INTO categories (name, max_budget_eur) VALUES ('Sonstiges', 0.0);